# Generated by Django 5.2 on 2026-02-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenkou', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walklog',
            name='steps',
            field=models.IntegerField(default=0),
        ),
    ]
