# Generated by Django 5.2 on 2026-02-05 14:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kenkou', '0002_alter_walklog_steps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='walklog',
            unique_together={('user', 'date')},
        ),
    ]
