# Generated by Django 5.2 on 2026-02-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenkou', '0003_alter_walklog_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walklog',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
    ]
