# Generated by Django 5.2 on 2026-02-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenkou', '0010_enemymaster_userenemy'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemymaster',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='enemies/'),
        ),
        migrations.DeleteModel(
            name='Enemy',
        ),
    ]
