# Generated by Django 5.2 on 2026-02-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kenkou', '0011_enemymaster_image_delete_enemy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemymaster',
            name='image',
        ),
    ]
