# Generated by Django 5.2 on 2026-02-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenkou', '0012_remove_enemymaster_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='name',
        ),
        migrations.AddField(
            model_name='enemymaster',
            name='image',
            field=models.ImageField(default='default_enemy.png', upload_to='enemies/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enemymaster',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='enemymaster',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
